### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by maletin** [lyckade/xpstart#19]
Traceback (most recent call last):
  File "X:\x-plane10\xpstart.py", line 2, in <module>
    import Tkinter
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 38, in <module>
    import FixTk
  File "C:\Python27\lib\lib-tk\FixTk.py", line 65, in <module>
    import _tkinter
ImportError: DLL load failed: %1 ist keine zulõssige Win32-Anwendung.

**Comment by maletin** [comment]
http://stackoverflow.com/questions/8724729/importerror-dll-load-failed-importing-tkinter
i deinstalled python 2.7.2 32bit and 2.7.8 64bit.
than i installed python 2.7.9 64 bit and everything is working fine.
